<?php
unset($_SESSION['l_name']);
unset($_SESSION['f_name']);
unset($_SESSION['phone']);
unset($_SESSION['user_id']);
unset($_SESSION['v_type']);
unset($_SESSION['reason']);
unset($_SESSION['v_class']);
unset($_SESSION['cell']);
unset($_SESSION['vol_sub']);
/*unset(
unset(
unset(
unset(
unset(
unset(
unset(*/
?>
